name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Linter (ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          .venv/bin/pip install -r requirements/dev.txt
          .venv/bin/pip install -e .
          .venv/bin/pip install --upgrade pip

      - name: Run Ruff
        run: |
          source .venv/bin/activate
          .venv/bin/ruff check src tests

  test:
    name: Tests (pytest + coverage)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          .venv/bin/pip install -r requirements/dev.txt
          .venv/bin/pip install -e .
          .venv/bin/pip install --upgrade pip

      - name: Run Tests
        run: |
          source .venv/bin/activate
          .venv/bin/pytest
