name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Linter (ruff)
    uses: ./.github/workflows/setup.yml
    secrets: inherit

  run-lint:
    name: Run Ruff
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Activate venv and run Ruff
        run: |
          source .venv/bin/activate
          .venv/bin/ruff check src tests

  test:
    name: Setup for Tests
    uses: ./.github/workflows/setup.yml
    secrets: inherit

  run-test:
    name: Run Pytest
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Activate venv and run tests
        run: |
          source .venv/bin/activate
          .venv/bin/pytest
