name: Setup Python and Install Dependencies

on:
  workflow_call:
    outputs:
      venv-path:
        description: "Path to the virtual environment"
        value: ".venv"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          .venv/bin/pip install -r requirements/dev.txt
          .venv/bin/pip install -e .
          .venv/bin/pip install --upgrade pip
